name: camcalib
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py39hcbf5309_0
  - cycler=0.10.0=py_2
  - freetype=2.10.4=h546665d_1
  - icu=68.1=h0e60522_0
  - intel-openmp=2021.2.0=h57928b3_616
  - jbig=2.1=h8d14728_2003
  - jpeg=9d=h8ffe710_0
  - kiwisolver=1.3.1=py39h2e07f2f_1
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=9_mkl
  - libpng=1.6.37=h1d00b33_2
  - libtiff=4.3.0=h0c97f57_1
  - lz4-c=1.9.3=h8ffe710_0
  - matplotlib=3.4.2=py39hcbf5309_0
  - matplotlib-base=3.4.2=py39h581301d_0
  - mkl=2021.2.0=hb70f87d_389
  - numpy=1.21.0=py39h6635163_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1k=h8ffe710_0
  - pillow=8.2.0=py39h1a9d4f7_1
  - pip=21.1.3=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py39hcbf5309_7
  - pyqt-impl=5.12.3=py39h415ef7b_7
  - pyqt5-sip=4.19.18=py39h415ef7b_7
  - pyqtchart=5.12=py39h415ef7b_7
  - pyqtwebengine=5.12.1=py39h415ef7b_7
  - python=3.9.5=h7840368_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.9=2_cp39
  - qt=5.12.9=h5909a2a_4
  - setuptools=49.6.0=py39hcbf5309_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h8ffe710_0
  - tbb=2021.2.0=h2d74725_1
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py39hb82d6ee_1
  - tqdm=4.61.1=pyhd8ed1ab_0
  - tzdata=2021a=he74cb21_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wheel=0.36.2=pyhd3deb0d_0
  - wincertstore=0.2=py39hcbf5309_1006
  - xz=5.2.5=h62dcd97_1
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.5.0=h6255e5f_0
prefix: C:\Users\hjoon\AppData\Local\Continuum\anaconda3\envs\camcalib

